package HrCenterApp.DEMSPackage;

/**
* HrCenterApp/DEMSPackage/LocationHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from DEMS.idl
* Wednesday, October 24, 2018 8:16:32 o'clock PM EDT
*/

public final class LocationHolder implements org.omg.CORBA.portable.Streamable
{
  public HrCenterApp.DEMSPackage.Location value = null;

  public LocationHolder ()
  {
  }

  public LocationHolder (HrCenterApp.DEMSPackage.Location initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = HrCenterApp.DEMSPackage.LocationHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    HrCenterApp.DEMSPackage.LocationHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return HrCenterApp.DEMSPackage.LocationHelper.type ();
  }

}
