package HrCenterApp.DEMSPackage;

/**
* HrCenterApp/DEMSPackage/ProjectHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from DEMS.idl
* Wednesday, October 24, 2018 6:25:07 o'clock PM EDT
*/

public final class ProjectHolder implements org.omg.CORBA.portable.Streamable
{
  public HrCenterApp.DEMSPackage.Project value = null;

  public ProjectHolder ()
  {
  }

  public ProjectHolder (HrCenterApp.DEMSPackage.Project initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = HrCenterApp.DEMSPackage.ProjectHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    HrCenterApp.DEMSPackage.ProjectHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return HrCenterApp.DEMSPackage.ProjectHelper.type ();
  }

}
