package HrCenterApp;


/**
* HrCenterApp/DEMSOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from DEMS.idl
* Monday, October 22, 2018 1:59:17 o'clock PM EDT
*/

public interface DEMSOperations 
{
  String createMRecord (String firstName, String lastName, String employeeID, String mailID, String managerID, HrCenterApp.DEMSPackage.Project[] projects, HrCenterApp.DEMSPackage.ServerLocation location);
  String createERecord (String firstName, String lastName, String employeeID, String mailID, String projectID, String managerID);
  String getRecordCounts (String managerID);
  String editRecord (String recordID, String fieldName, String newValue);
  String transferRecord (String managerID, String recordID, HrCenterApp.DEMSPackage.ServerLocation location);
  void shutdown ();
} // interface DEMSOperations
