package HrCenterApp;

/**
* HrCenterApp/DEMSHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from DEMS.idl
* Monday, October 22, 2018 12:50:39 o'clock PM EDT
*/

public final class DEMSHolder implements org.omg.CORBA.portable.Streamable
{
  public HrCenterApp.DEMS value = null;

  public DEMSHolder ()
  {
  }

  public DEMSHolder (HrCenterApp.DEMS initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = HrCenterApp.DEMSHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    HrCenterApp.DEMSHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return HrCenterApp.DEMSHelper.type ();
  }

}
